# Bitwise
print("\n--- Bitwise Operators ---")
a=int (input("enter the value:"))
b=int (input("enter another value"))
print("a & b =", a & b)
print("a | b =", a | b)
print("a ^ b =", a ^ b)
print("~a =", ~a)
print("a << 1 =", a << 1)
print("a >> 1 =", a >> 1)
